### ISSUE TITLE
Not able to upload the file using easy-backblaze 

### ISSUE THREAD

**Issue by LovikaJain** [jamesloper/easy-backblaze#2]
Hi I am trying to upload an image from my local drive to backblaze-b2 but I want to load the file from insomnia (mutipart/form Input) using hapijs. 

Currently When I try to mention the path by b2.uploadFile(files[key].hapi.filename) but by this I get the path of the current directory. 
Do I need to upload the file to the server first or can it be done directly as well?
File : C:/Users/Lovika/Desktop/addDriver.png
Code :
var b2 = new B2('accountId', 'applicationKey');

b2.uploadFile('files[key].hapi.filename', {
    name: 'addDriver.png', // Optional, renames file
    bucket: 'testBucket', // Optional, defaults to first bucket
}, function(err, res) {
    console.log('Done!', err, res);
});

error : path doesn't exist

**Comment by lemontron** [comment]
Check the first param you have quote marks around your variable?? looks like you are passing a string literal not the value itself
